# Sử dụng Python slim để nhẹ
FROM python:3.10-slim

# Cài thư viện cần thiết
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Chạy script chính
CMD ["python", "stream_to_kafka.py"]
