indices =["VNCOND","VNCONS","VNDIAMOND","VNENE","VNFIN","VNFINLEAD",
          "VNFINSELECT","VNHEAL","VNIND","VNIT","VNMAT","VNMIDCAP",
          "VNREAL","VNSI","VNSMALLCAP","VNUTI","VNX50","VNXALLSHARE"]
