# <INDICES START>
indices_map = {
    'VNINDEX': [
        'AAA','AAM','AAN','AAT','ABR','ABS','ABT','ACB','ACC','ACG','ACL','ADG','ADP','ADS','AFX','AGG',
        'AGR','ANT','ANV','APG','APH','ASG','ASM','ASP','AST','BAF','BCE','BCG','BCM','BFC','BHN','BIC',
        'BID','BKG','BMC','BMI','BMP','BRC','BSI','BSR','BTP','BTT','BVH','BWE','C32','C47','CCC','CCI',
        'CCL','CDC','CHP','CIG','CII','CKG','CLC','CLL','CLW','CMG','CMV','CMX','CNG','COM','CRC','CRE',
        'CRV','CSM','CSV','CTD','CTF','CTG','CTI','CTR','CTS','CVT','D2D','DAH','DAT','DBC','DBD','DBT',
        'DC4','DCL','DCM','DGC','DGW','DHA','DHC','DHG','DHM','DIG','DLG','DMC','DPG','DPM','DPR','DQC',
        'DRC','DRH','DRL','DSC','DSE','DSN','DTA','DTL','DTT','DVP','DXG','DXS','DXV','EIB','ELC','EVE',
        'EVF','EVG','FCM','FCN','FDC','FIR','FIT','FMC','FPT','FRT','FTS','GAS','GDT','GEE','GEG','GEL',
        'GEX','GHC','GIL','GMD','GMH','GSP','GTA','GVR','HAG','HAH','HAP','HAR','HAS','HAX','HCD','HCM',
        'HDB','HDC','HDG','HHP','HHS','HHV','HID','HII','HMC','HNA','HPA','HPG','HPX','HQC','HRC','HSG',
        'HSL','HT1','HTG','HTI','HTL','HTN','HTV','HU1','HUB','HVH','HVN','ICT','IDI','IJC','ILB','IMP',
        'ITC','ITD','JVC','KBC','KDC','KDH','KHG','KHP','KLB','KMR','KOS','KSB','L10','LAF','LBM','LCG',
        'LDG','LGC','LGL','LHG','LIX','LM8','LPB','LSS','MBB','MCH','MCM','MCP','MDG','MHC','MIG','MSB',
        'MSH','MSN','MWG','MZG','NAB','NAF','NAV','NBB','NCT','NHA','NHH','NHT','NKG','NLG','NNC','NO1',
        'NSC','NT2','NTC','NTL','NVL','NVT','OCB','OGC','OPC','ORS','PAC','PAN','PC1','PDN','PDR','PDV',
        'PET','PGC','PGD','PGI','PGV','PHC','PHR','PIT','PJT','PLP','PLX','PMG','PNC','PNJ','POW','PPC',
        'PTB','PTC','PTL','PVD','PVP','PVT','QCG','QNP','RAL','REE','RYG','S4A','SAB','SAM','SAV','SBA',
        'SBG','SBT','SBV','SC5','SCR','SCS','SFC','SFG','SFI','SGN','SGR','SGT','SHA','SHB','SHI','SHP',
        'SIP','SJD','SJS','SKG','SMA','SMB','SMC','SPM','SRC','SRF','SSB','SSC','SSI','ST8','STB','STG',
        'STK','SVC','SVD','SVT','SZC','SZL','TAL','TBC','TCB','TCD','TCH','TCI','TCL','TCM','TCO','TCR',
        'TCT','TCX','TDC','TDG','TDH','TDM','TDP','TDW','TEG','THG','TIP','TIX','TLD','TLG','TLH','TMP',
        'TMS','TMT','TN1','TNC','TNH','TNI','TNT','TPB','TPC','TRA','TRC','TSA','TSC','TTA','TTE','TTF',
        'TV2','TVB','TVS','TVT','TYA','UIC','VAB','VCA','VCB','VCF','VCG','VCI','VCK','VDP','VDS','VFG',
        'VGC','VHC','VHM','VIB','VIC','VID','VIP','VIX','VJC','VMD','VND','VNG','VNL','VNM','VNS','VOS',
        'VPB','VPD','VPG','VPH','VPI','VPL','VPS','VPX','VRC','VRE','VSC','VSH','VSI','VTB','VTO','VTP',
        'VVS','YBM','YEG',
],
    'HNXINDEX': [
        'ADC','ALT','AMC','AME','AMV','API','APS','ARM','ATS','BAB','BAX','BBS','BCC','BCF','BED','BKC',
        'BNA','BPC','BTS','BTW','BVS','BXH','C69','CAG','CAN','CAP','CAR','CCR','CDN','CEO','CET','CIA',
        'CJC','CKV','CLH','CLM','CMC','CMS','CPC','CSC','CST','CTB','CTP','CTT','CX8','D11','DAD','DAE',
        'DC2','DHP','DHT','DIH','DL1','DNC','DNP','DP3','DS3','DST','DTD','DTG','DTK','DVM','DXP','EBS',
        'ECI','EID','EVS','FID','GDW','GIC','GKM','GLT','GMA','GMX','HAD','HAT','HBS','HCC','HCT','HDA',
        'HEV','HGM','HHC','HJS','HKT','HLC','HLD','HMH','HMR','HOM','HTC','HUT','HVT','ICG','IDC','IDJ',
        'IDV','INC','INN','IPA','ITQ','IVS','KDM','KHS','KKC','KMT','KSD','KSF','KST','KSV','KTS','L14',
        'L18','L40','LAS','LBE','LCD','LDP','LHC','LIG','MAC','MAS','MBG','MBS','MCC','MCF','MCO','MDC',
        'MED','MEL','MIC','MKV','MST','MVB','NAG','NAP','NBC','NBP','NBW','NDN','NDX','NET','NFC','NHC',
        'NRC','NSH','NST','NTH','NTP','NVB','OCH','ONE','PBP','PCE','PCH','PCT','PDB','PEN','PGN','PGS',
        'PGT','PHN','PIA','PIC','PJC','PLC','PMB','PMC','PMP','PMS','POT','PPE','PPP','PPS','PPT','PPY',
        'PRC','PRE','PSC','PSD','PSE','PSI','PSW','PTD','PTI','PTS','PTX','PV2','PVB','PVC','PVG','PVI',
        'PVS','QHD','QST','QTC','RCL','S55','S99','SAF','SCG','SCI','SD5','SD9','SDC','SDG','SDN','SDU',
        'SEB','SED','SFN','SGC','SGD','SGH','SHE','SHN','SHS','SJ1','SJE','SLS','SMN','SMT','SPC','SRA',
        'SSM','STC','STP','SVN','SZB','TA9','TD6','TDT','TET','TFC','THB','THD','THS','THT','TIG','TJC',
        'TKU','TMB','TMC','TMX','TNG','TOT','TPP','TSB','TTC','TTH','TTL','TTT','TV3','TV4','TVC','TVD',
        'TXM','UNI','V12','V21','VBC','VC1','VC2','VC3','VC6','VC7','VC9','VCC','VCM','VCS','VDL','VE1',
        'VE3','VE4','VFS','VGP','VGS','VHE','VHL','VIF','VIG','VIT','VLA','VMC','VMS','VNC','VNF','VNR',
        'VNT','VSA','VSM','VTC','VTH','VTJ','VTV','VTZ','WCS','WSS','X20',
],
    'UPCOMINDEX': [
        'A32','AAH','AAS','AAV','ABB','ABC','ABI','ABW','ACE','ACM','ACS','ACV','AG1','AGF','AGM','AGP',
        'AGX','AIC','AIG','ALC','ALV','AMP','AMS','ANI','APC','APF','APL','APP','APT','ART','ATA','ATG',
        'AVC','AVG','BAL','BBH','BBM','BBT','BCA','BCB','BCP','BCR','BCV','BDG','BDT','BDW','BEL','BGE',
        'BGW','BHA','BHC','BHG','BHH','BHI','BHK','BHP','BIG','BIO','BLF','BLI','BLN','BLT','BMD','BMF',
        'BMG','BMJ','BMK','BMS','BMV','BNW','BOT','BQB','BQP','BRR','BRS','BSA','BSD','BSG','BSH','BSL',
        'BSP','BSQ','BT1','BT6','BTB','BTD','BTG','BTH','BTN','BTU','BTV','BVG','BVL','BVN','BWA','BWS',
        'C21','C22','C4G','C92','CAD','CAT','CBI','CBS','CC1','CCA','CCM','CCP','CCS','CCT','CCV','CDG',
        'CDO','CDP','CDR','CEN','CFM','CFV','CGV','CH5','CHC','CHS','CI5','CID','CIP','CK8','CKA','CKD',
        'CLI','CLX','CMD','CMF','CMI','CMK','CMM','CMN','CMP','CMT','CMW','CNA','CNC','CNN','CNT','CPA',
        'CPH','CPI','CQN','CQT','CSI','CT3','CT6','CTW','CTX','CVN','CYC','DAC','DAG','DAN','DAS','DBM',
        'DC1','DCF','DCG','DCH','DCR','DCS','DCT','DCV','DDB','DDG','DDH','DDM','DDN','DDV','DFC','DFF',
        'DGT','DHB','DHD','DHN','DIC','DID','DKC','DKG','DLD','DLR','DLT','DM7','DMN','DNA','DND','DNE',
        'DNH','DNL','DNM','DNN','DNT','DNW','DOC','DOP','DP1','DP2','DPC','DPH','DPP','DRG','DRI','DSD',
        'DSG','DSH','DSP','DTC','DTH','DTI','DTP','DUS','DVC','DVG','DVN','DVT','DVW','DWC','DWS','DXL',
        'E12','E29','ECO','EFI','EGL','EIC','EIN','EME','EMG','EMS','F88','FBC','FCC','FCS','FGL','FHN',
        'FHS','FIC','FOC','FOX','FRC','FRM','FSO','FT1','FTI','FTM','G20','G36','GCB','GCF','GDA','GDH',
        'GER','GGG','GH3','GLC','GLW','GMC','GND','GPC','GSM','GTD','GTS','GTT','GVT','H11','HAC','HAF',
        'HAM','HAN','HAV','HBC','HBD','HBH','HC1','HC3','HCI','HD2','HD6','HD8','HDM','HDP','HDW','HEC',
        'HEJ','HEP','HES','HFB','HFC','HFX','HGT','HHB','HHG','HHN','HIO','HJC','HKB','HLA','HLB','HLO',
        'HLS','HLT','HLY','HMD','HMG','HMS','HNB','HND','HNF','HNG','HNI','HNM','HNP','HNR','HOT','HPB',
        'HPD','HPH','HPI','HPO','HPP','HPT','HPW','HRB','HSA','HSM','HSP','HSV','HTE','HTM','HTP','HTT',
        'HU3','HU4','HU6','HUG','HVA','HVX','HWS','IBD','ICC','ICF','ICI','ICN','IDP','IFS','ILA','ILC',
        'ILS','IME','IN4','IRC','ISG','ISH','IST','ITA','ITS','JOS','KCB','KGM','KHD','KHW','KHX','KIP',
        'KPF','KSQ','KTC','KTL','KTT','KVC','L12','L35','L43','L45','L61','L62','L63','LAI','LAW','LCM',
        'LDW','LEC','LG9','LIC','LKW','LLM','LM3','LM7','LMC','LMH','LMI','LNC','LO5','LPT','LQN','LSG',
        'LTC','LTG','LUT','M10','MA1','MBN','MBT','MCG','MDA','MDF','MEC','MEF','MES','MFS','MGC','MGG',
        'MGR','MH3','MHL','MIE','MKP','MLC','MLS','MML','MNB','MND','MPC','MPT','MPY','MQB','MQN','MRF',
        'MSR','MTA','MTB','MTG','MTH','MTL','MTP','MTS','MTV','MVC','MVN','NAC','NAS','NAU','NAW','NBE',
        'NBT','NCG','NCS','ND2','NDC','NDF','NDP','NDT','NDW','NED','NGC','NHD','NHV','NJC','NLS','NNT',
        'NOS','NQB','NQN','NSG','NSL','NSS','NTF','NTT','NTW','NUE','NVP','NWT','NXT','ODE','OIL','ONW',
        'PAI','PAP','PAS','PAT','PBC','PBT','PCC','PCF','PCG','PCM','PDC','PEG','PEQ','PFL','PGB','PHH',
        'PHP','PHS','PID','PIS','PIV','PJS','PLA','PLE','PLO','PMJ','PMT','PMW','PND','PNG','PNP','PNT',
        'POB','POM','POS','POV','PPH','PPI','PQN','PRO','PRT','PSB','PSH','PSL','PSN','PSP','PTE','PTG',
        'PTH','PTM','PTO','PTP','PTT','PTV','PVE','PVH','PVL','PVM','PVO','PVR','PVV','PVX','PVY','PWA',
        'PWS','PXA','PXI','PXL','PXM','PXS','PXT','QBS','QCC','QHW','QNC','QNS','QNT','QNU','QNW','QPH',
        'QSP','QTP','RAT','RBC','RCC','RCD','RDP','RGG','RIC','RTB','S12','S72','S74','SAC','SAL','SAS',
        'SB1','SBB','SBD','SBH','SBL','SBM','SBR','SBS','SCC','SCD','SCJ','SCL','SCO','SD2','SD3','SD4',
        'SD6','SD7','SD8','SDA','SDD','SDK','SDP','SDT','SDV','SDY','SEA','SEP','SGB','SGI','SGP','SGS',
        'SHC','SID','SIG','SII','SIV','SJF','SJG','SJM','SKH','SKN','SKV','SLD','SNC','SNZ','SP2','SPB',
        'SPD','SPH','SPI','SPV','SRB','SSG','SSH','STD','STH','STS','STT','STW','SVG','SVH','SWC','SZE',
        'SZG','TA6','TAB','TAN','TAR','TAW','TBD','TBR','TBW','TCJ','TCK','TCW','TDB','TDF','TDS','TED',
        'TGG','TGP','TH1','THM','THN','THP','THU','THW','TID','TIE','TIN','TIS','TKA','TL4','TLP','TMG',
        'TMW','TNA','TNB','TNP','TNS','TNW','TOP','TOS','TOW','TPS','TQW','TR1','TRS','TRT','TRV','TS3',
        'TSD','TSG','TSJ','TST','TT6','TTB','TTD','TTG','TTN','TTS','TTZ','TUG','TV1','TV6','TVA','TVG',
        'TVH','TVM','TVN','TW3','UCT','UDC','UDJ','UDL','UEM','UMC','UPC','UPH','UPS','USC','USD','UTT',
        'UXC','VAF','VAV','VBG','VBH','VBT','VCE','VCP','VCR','VCT','VCX','VDB','VDG','VDN','VDT','VE2',
        'VE8','VE9','VEA','VEC','VEF','VES','VET','VFC','VFR','VGG','VGI','VGL','VGR','VGT','VGV','VHD',
        'VHF','VHG','VHH','VIE','VIM','VIN','VIR','VIW','VKC','VLB','VLC','VLG','VLP','VLS','VLW','VMA',
        'VMG','VMK','VMT','VNA','VNB','VNE','VNH','VNI','VNP','VNX','VNY','VNZ','VPA','VPC','VPR','VPW',
        'VQC','VRG','VSE','VSF','VSG','VSN','VST','VTA','VTD','VTE','VTG','VTI','VTK','VTM','VTQ','VTR',
        'VTS','VTX','VUA','VVN','VW3','VWS','VXB','VXP','VXT','WSB','WTC','X26','X77','XDH','XHC','XLV',
        'XMC','XMD','XMP','XPH','YBC','YTC',
],
    'VN100': [
        'ACB','ANV','BAF','BCM','BID','BMP','BSI','BSR','BVH','BWE','CII','CMG','CTD','CTG','CTR','CTS',
        'DBC','DCM','DGW','DIG','DPM','DSE','DXG','DXS','EIB','EVF','FPT','FRT','FTS','GAS','GEE','GEX',
        'GMD','GVR','HAG','HCM','HDB','HDC','HDG','HHV','HPG','HSG','HT1','IMP','KBC','KDC','KDH','KOS',
        'LPB','MBB','MSB','MSN','MWG','NAB','NKG','NLG','NT2','NVL','OCB','PAN','PC1','PDR','PHR','PLX',
        'PNJ','POW','PVD','PVT','REE','SAB','SBT','SCS','SHB','SIP','SJS','SSB','SSI','STB','SZC','TCB',
        'TCH','TPB','VCB','VCG','VCI','VGC','VHC','VHM','VIB','VIC','VIX','VJC','VND','VNM','VPB','VPI',
        'VPL','VRE','VSC','VTP',
],
    'VN30': [
        'ACB','BID','BSR','CTG','FPT','GAS','GVR','HDB','HPG','LPB','MBB','MSN','MWG','PLX','SAB','SHB',
        'SSB','SSI','STB','TCB','TPB','VCB','VHM','VIB','VIC','VJC','VNM','VPB','VPL','VRE',
],
    'VNALLSHARE': [
        'AAA','AAM','ABT','ACB','ACC','ACL','ADG','ADP','ADS','AGG','AGR','ANV','APG','APH','ASM','ASP',
        'AST','BAF','BCE','BCM','BFC','BIC','BID','BKG','BMC','BMI','BMP','BRC','BSI','BSR','BTP','BVH',
        'BWE','C32','CCC','CCL','CDC','CHP','CIG','CII','CKG','CLL','CMG','CMX','CNG','CRC','CRE','CSM',
        'CSV','CTD','CTF','CTG','CTI','CTR','CTS','D2D','DAH','DBC','DBD','DC4','DCL','DCM','DGW','DHA',
        'DHC','DHM','DIG','DLG','DMC','DPG','DPM','DPR','DRC','DRL','DSC','DSE','DSN','DTA','DVP','DXG',
        'DXS','DXV','EIB','ELC','EVE','EVF','EVG','FCM','FCN','FIR','FIT','FMC','FPT','FRT','FTS','GAS',
        'GDT','GEE','GEG','GEX','GIL','GMD','GSP','GVR','HAG','HAH','HAP','HAR','HAX','HCD','HCM','HDB',
        'HDC','HDG','HHP','HHS','HHV','HID','HII','HMC','HPG','HPX','HQC','HSG','HSL','HT1','HTG','HTI',
        'HTN','HTV','HUB','HVH','ICT','IDI','IJC','ILB','IMP','ITC','ITD','JVC','KBC','KDC','KDH','KHG',
        'KHP','KMR','KOS','KSB','LAF','LBM','LCG','LGL','LHG','LIX','LPB','LSS','MBB','MCM','MCP','MHC',
        'MIG','MSB','MSH','MSN','MWG','NAB','NAF','NAV','NBB','NCT','NHA','NHH','NKG','NLG','NNC','NO1',
        'NSC','NT2','NTL','NVL','OCB','OGC','ORS','PAC','PAN','PC1','PDR','PET','PGC','PHC','PHR','PIT',
        'PLP','PLX','PNJ','POW','PPC','PTB','PTC','PTL','PVD','PVP','PVT','QCG','RAL','REE','RYG','SAB',
        'SAM','SAV','SBG','SBT','SCR','SCS','SFC','SFI','SGN','SGR','SGT','SHA','SHB','SHI','SIP','SJD',
        'SJS','SKG','SMB','SSB','SSI','ST8','STB','STK','SVD','SVT','SZC','SZL','TCB','TCH','TCI','TCL',
        'TCM','TCO','TCT','TDC','TDG','TDH','TDP','TEG','THG','TIP','TLD','TLG','TLH','TMT','TN1','TNH',
        'TNI','TNT','TPB','TRC','TSC','TTA','TTF','TV2','TVB','TVS','UIC','VCA','VCB','VCG','VCI','VDS',
        'VFG','VGC','VHC','VHM','VIB','VIC','VIP','VIX','VJC','VND','VNL','VNM','VOS','VPB','VPG','VPH',
        'VPI','VPL','VPS','VRC','VRE','VSC','VSI','VTB','VTO','VTP','YBM','YEG',
],
    'VNCOND': [
        'ADS','AST','CSM','CTF','DAH','DRC','DSN','EVE','FRT','GDT','GIL','HAX','HHS','HTG','KMR','MSH',
        'MWG','PAC','PNJ','PTB','SAV','SFC','STK','SVD','SVT','TCM','TCT','TMT','TTF','VPL','VTB',
],
    'VNCONS': [
        'AAM','ABT','ACL','ANV','BAF','CMX','DBC','FMC','HAG','HSL','IDI','KDC','LAF','LIX','LSS','MCM',
        'MSN','NAF','NSC','PAN','SAB','SBT','SMB','VHC','VNM',
],
    'VNDIAMOND': [
        'ACB','BMP','CTD','CTG','FPT','GMD','HDB','KDH','MBB','MSB','MWG','NLG','OCB','PNJ','REE','TCB',
        'TPB','VPB',
],
    'VNENE': [
        'ASP','BSR','CNG','GSP','PGC','PLX','PVD','PVP','PVT','TDG',
],
    'VNFIN': [
        'ACB','AGR','APG','BIC','BID','BMI','BSI','BVH','CTG','CTS','DSC','DSE','EIB','EVF','FIT','FTS',
        'HCM','HDB','LPB','MBB','MIG','MSB','NAB','OCB','OGC','ORS','SHB','SSB','SSI','STB','TCB','TCI',
        'TPB','TVB','TVS','VCB','VCI','VDS','VIB','VIX','VND','VPB',
],
    'VNFINLEAD': [
        'ACB','BID','CTG','EIB','HCM','HDB','LPB','MBB','MSB','NAB','OCB','SHB','SSB','SSI','STB','TCB',
        'TPB','VCB','VCI','VIB','VIX','VND','VPB',
],
    'VNFINSELECT': [
        'ACB','AGR','APG','BIC','BID','BMI','BSI','BVH','CTG','CTS','DSC','DSE','EIB','EVF','FIT','FTS',
        'HCM','HDB','LPB','MBB','MIG','MSB','NAB','OCB','OGC','ORS','SHB','SSB','SSI','STB','TCB','TCI',
        'TPB','TVS','VCB','VCI','VDS','VIB','VIX','VND','VPB',
],
    'VNHEAL': [
        'DBD','DCL','DMC','IMP','JVC','TNH',
],
    'VNIND': [
        'BCE','BKG','BMP','BRC','C32','CCC','CDC','CII','CLL','CTD','CTR','DC4','DIG','DLG','DPG','DVP',
        'EVG','FCN','GEE','GEX','GMD','HAH','HCD','HDG','HHV','HID','HTI','HTN','HTV','HUB','HVH','IJC',
        'ILB','ITD','LCG','LGL','MHC','NCT','NHA','NO1','PC1','PET','PHC','PIT','PTC','RAL','REE','RYG',
        'SAM','SBG','SCS','SFI','SGN','SHA','SHI','SKG','ST8','SZC','TCH','TCL','TCO','TIP','TLG','TNI',
        'TSC','TV2','VCG','VGC','VIP','VJC','VNL','VOS','VPG','VRC','VSC','VSI','VTO','VTP',
],
    'HNX30': [
        'BVS','CAP','CEO','DP3','DTD','DVM','DXP','HUT','IDC','IDV','L14','L18','LAS','LHC','MBS','NDN',
        'NTP','PLC','PSD','PVB','PVC','PVS','SHS','SLS','TMB','TNG','TVD','VC3','VCS','VFS',
],
    'VNIT': [
        'CMG','DGW','ELC','FPT','ICT',
],
    'VNMAT': [
        'AAA','ACC','ADP','APH','BFC','BMC','CRC','CSV','CTI','DCM','DHA','DHC','DHM','DPM','DPR','DXV',
        'FCM','GVR','HAP','HHP','HII','HMC','HPG','HSG','HT1','KSB','LBM','MCP','NAV','NHH','NKG','NNC',
        'PHR','PLP','TDP','THG','TLD','TLH','TNT','TRC','VCA','VFG','VPS','YBM',
],
    'VNMIDCAP': [
        'ANV','BAF','BCM','BMP','BSI','BVH','BWE','CII','CMG','CTD','CTR','CTS','DBC','DCM','DGW','DIG',
        'DPM','DSE','DXG','DXS','EIB','EVF','FRT','FTS','GEE','GEX','GMD','HAG','HCM','HDC','HDG','HHV',
        'HSG','HT1','IMP','KBC','KDC','KDH','KOS','MSB','NAB','NKG','NLG','NT2','NVL','OCB','PAN','PC1',
        'PDR','PHR','PNJ','POW','PVD','PVT','REE','SBT','SCS','SIP','SJS','SZC','TCH','VCG','VCI','VGC',
        'VHC','VIX','VND','VPI','VSC','VTP',
],
    'VNREAL': [
        'AGG','ASM','BCM','CCL','CIG','CKG','CRE','D2D','DTA','DXG','DXS','FIR','HAR','HDC','HPX','HQC',
        'ITC','KBC','KDH','KHG','KOS','LHG','NBB','NLG','NTL','NVL','PDR','PTL','QCG','SCR','SGR','SIP',
        'SJS','SZL','TDC','TDH','TEG','TN1','VHM','VIC','VPH','VPI','VRE',
],
    'VNSI': [
        'BCM','BID','BMP','BVH','CTD','CTG','DCM','GEX','HDB','IMP','MBB','MWG','PAN','PVD','SBT','TCB',
        'VCB','VIC','VNM','VPB',
],
    'VNSMALLCAP': [
        'AAA','AAM','ABT','ACC','ACL','ADG','ADP','ADS','AGG','AGR','APG','APH','ASM','ASP','AST','BCE',
        'BFC','BIC','BKG','BMC','BMI','BRC','BTP','C32','CCC','CCL','CDC','CHP','CIG','CKG','CLL','CMX',
        'CNG','CRC','CRE','CSM','CSV','CTF','CTI','D2D','DAH','DBD','DC4','DCL','DHA','DHC','DHM','DLG',
        'DMC','DPG','DPR','DRC','DRL','DSC','DSN','DTA','DVP','DXV','ELC','EVE','EVG','FCM','FCN','FIR',
        'FIT','FMC','GDT','GEG','GIL','GSP','HAH','HAP','HAR','HAX','HCD','HHP','HHS','HID','HII','HMC',
        'HPX','HQC','HSL','HTG','HTI','HTN','HTV','HUB','HVH','ICT','IDI','IJC','ILB','ITC','ITD','JVC',
        'KHG','KHP','KMR','KSB','LAF','LBM','LCG','LGL','LHG','LIX','LSS','MCM','MCP','MHC','MIG','MSH',
        'NAF','NAV','NBB','NCT','NHA','NHH','NNC','NO1','NSC','NTL','OGC','ORS','PAC','PET','PGC','PHC',
        'PIT','PLP','PPC','PTB','PTC','PTL','PVP','QCG','RAL','RYG','SAM','SAV','SBG','SCR','SFC','SFI',
        'SGN','SGR','SGT','SHA','SHI','SJD','SKG','SMB','ST8','STK','SVD','SVT','SZL','TCI','TCL','TCM',
        'TCO','TCT','TDC','TDG','TDH','TDP','TEG','THG','TIP','TLD','TLG','TLH','TMT','TN1','TNH','TNI',
        'TNT','TRC','TSC','TTA','TTF','TV2','TVB','TVS','UIC','VCA','VDS','VFG','VIP','VNL','VOS','VPG',
        'VPH','VPS','VRC','VSI','VTB','VTO','YBM','YEG',
],
    'VNUTI': [
        'BTP','BWE','CHP','DRL','GAS','GEG','KHP','NT2','POW','PPC','SJD','TTA','UIC',
],
    'VNX50': [
        'ACB','BID','BSR','CTG','DCM','DPM','DXG','EIB','FPT','FRT','GEE','GEX','GMD','HCM','HDB','HPG',
        'IDC','KBC','KDH','LPB','MBB','MSB','MSN','MWG','NLG','NVL','PDR','PLX','PNJ','POW','PVS','SHB',
        'SHS','SSI','STB','TCB','TPB','VCB','VCG','VCI','VHM','VIB','VIC','VIX','VJC','VND','VNM','VPB',
        'VPI','VRE',
],
    'VNXALLSHARE': [
        'AAA','AAM','ABT','ACB','ACC','ACG','ACL','ADG','ADP','ADS','AGG','AGR','AMC','ANV','APG','APH',
        'ASM','ASP','AST','BAF','BCE','BFC','BIC','BID','BKC','BKG','BMC','BMI','BMP','BPC','BRC','BSI',
        'BSR','BTP','BVH','BVS','BWE','C32','C69','CAG','CAP','CCC','CCL','CDC','CEO','CHP','CIA','CIG',
        'CII','CKG','CKV','CLC','CLH','CLL','CMC','CMG','CMS','CMV','CMX','CNG','CPC','CRC','CRE','CSC',
        'CSM','CST','CSV','CTD','CTF','CTG','CTI','CTP','CTR','CTS','D11','D2D','DAD','DAH','DAT','DBC',
        'DBD','DBT','DC4','DCL','DCM','DGW','DHA','DHC','DHG','DHM','DHT','DIG','DIH','DL1','DLG','DMC',
        'DP3','DPG','DPM','DPR','DRC','DRL','DSC','DSE','DSN','DST','DTA','DTD','DTG','DTL','DTT','DVM',
        'DVP','DXG','DXP','DXS','DXV','EBS','EIB','EID','ELC','EVE','EVF','EVG','EVS','FCM','FCN','FIR',
        'FIT','FMC','FPT','FRT','FTS','GDT','GEE','GEG','GEX','GIC','GIL','GLT','GMD','GMH','GMX','GSP',
        'HAG','HAH','HAP','HAR','HAX','HCC','HCD','HCM','HDA','HDB','HDC','HDG','HGM','HHP','HHS','HHV',
        'HID','HII','HKT','HLC','HLD','HMC','HMR','HOM','HPG','HPX','HQC','HRC','HSG','HSL','HT1','HTG',
        'HTI','HTL','HTN','HTV','HU1','HUB','HUT','HVH','HVT','ICG','ICT','IDC','IDI','IDV','IJC','ILB',
        'IMP','IPA','ITC','ITD','ITQ','IVS','JVC','KBC','KDC','KDH','KDM','KHG','KHP','KHS','KKC','KMR',
        'KOS','KSB','KSD','L14','L18','L40','LAF','LAS','LBE','LBM','LCG','LGL','LHC','LHG','LIG','LIX',
        'LPB','LSS','MAC','MBB','MBG','MBS','MCF','MCM','MCO','MCP','MDC','MDG','MHC','MIC','MIG','MKV',
        'MSB','MSH','MSN','MST','MWG','NAB','NAF','NAG','NAV','NBB','NBC','NCT','NDN','NDX','NET','NFC',
        'NHA','NHH','NKG','NLG','NNC','NO1','NRC','NSC','NSH','NST','NT2','NTL','NTP','NVL','NVT','OCB',
        'OGC','ONE','ORS','PAC','PAN','PBP','PC1','PCE','PCH','PCT','PDB','PDN','PDR','PET','PGC','PGI',
        'PGN','PHC','PHR','PIC','PIT','PJT','PLC','PLP','PLX','PMB','PMC','PMG','PMS','PNC','PNJ','POT',
        'POW','PPC','PPS','PPT','PRC','PRE','PSD','PSE','PSI','PSW','PTB','PTC','PTS','PVB','PVC','PVD',
        'PVG','PVI','PVP','PVS','PVT','QCG','QNP','QTC','RAL','RCL','REE','RYG','S99','SAB','SAF','SAM',
        'SAV','SBA','SBG','SBT','SCG','SCI','SCR','SCS','SD5','SD9','SED','SFC','SFG','SFI','SGC','SGN',
        'SGR','SGT','SHA','SHB','SHE','SHI','SHN','SHP','SHS','SIP','SJD','SJE','SJS','SKG','SLS','SMB',
        'SMN','SPM','SRC','SSB','SSI','ST8','STB','STK','SVC','SVD','SVN','SVT','SZB','SZC','SZL','TA9',
        'TAL','TBC','TCB','TCH','TCI','TCL','TCM','TCO','TCT','TD6','TDC','TDG','TDH','TDM','TDP','TDT',
        'TEG','TFC','THG','THT','TIG','TIP','TKU','TLD','TLG','TLH','TMB','TMP','TMT','TN1','TNC','TNG',
        'TNH','TNI','TNT','TOT','TPB','TPC','TRA','TRC','TSB','TSC','TTA','TTC','TTF','TTL','TTT','TV2',
        'TV3','TV4','TVB','TVC','TVD','TVS','TVT','TYA','UIC','UNI','VAB','VC3','VC6','VC7','VCA','VCB',
        'VCC','VCG','VCI','VCS','VDP','VDS','VFG','VFS','VGC','VGP','VGS','VHC','VHE','VHM','VIB','VIC',
        'VID','VIF','VIP','VIX','VJC','VMC','VMS','VNC','VND','VNF','VNL','VNM','VNR','VNS','VOS','VPB',
        'VPD','VPG','VPH','VPI','VPL','VPS','VRC','VRE','VSA','VSC','VSH','VSI','VSM','VTB','VTC','VTH',
        'VTO','VTP','VTZ','WCS','WSS','X20','YBM','YEG',
],
# <INDICES END>

# <INDICES_DERIVATIVES START>
    'FUTUREINDEX':[
        '41B5G3000',	'41B5G6000',	'41BAG3000',	'41BAG6000',	'41I1G1000',	'41I1G3000',	'41I1G6000',	'41I2FC000',	'41I2G1000',	'41I2G3000',
        '41I2G6000',	'GB05F2512',	'GB10F2512',	'VN30F2512',
    ],
    'FUTURETPCP':[
        '41B5G3000',	'41B5G6000',	'41BAG3000',	'41BAG6000',	'GB05F2512',	'GB10F2512',
    ]
# <INDICES_DERIVATIVES END>

}
